kuberUi: http://localhost:4326
kuberRest: http://localhost:9091
kuberWs: ws://localhost:9091
spitfireRest: http://localhost:8080
spitfireWs: ws://localhost:8080
database:
  connectionUri: "database connection uri"
server:
  port: 8080
